### ISSUE TITLE
Modelo entidade relacionamento 

### ISSUE THREAD

**Issue by feliperasilva** [Vini1227/MQA#21]
EU como desenvolvedor
QUERO criar o MER do banco de dados
PARA representar de forma efetiva o ambiente real no banco de dados

- [x] Diagramar o MER no Br Modelos
- [x] Definir as entidades
- [x] Definir os relacionamentos
- [x] Definir as cardinalidades

**Comment by feliperasilva** [comment]
Link para o modelo entidade e relacionamento: https://app.brmodeloweb.com/#!/publicview/675b96f17015212f7df2178d

**Comment by Ryonxl** [comment]
Iremos refazer o MER

**Comment by Ryonxl** [comment]
Modelo MER refeito: https://app.brmodeloweb.com/#!/conceptual/6765521566b28950ec24fb59
