### ISSUE TITLE
Definição de identidade visual do projeto

### ISSUE THREAD

**Issue by feliperasilva** [Vini1227/MQA#23]
EU como desenvolvedor
QUERO criar uma identidade visual 
PARA que a aplicação tenha fácil identificação visual

- [x] Prototipação no figma
- [x] Definir a paleta de cores
- [x] Definir fontes
- [x] Padronizar botões

**Comment by Ryonxl** [comment]
https://www.figma.com/design/teP23Z4WHPKNd1r8sA4gLK/Projeto-1?node-id=0-1&t=BwasoQFLGRe3Ejp6-1
